import jsPDF from 'jspdf';

export function generateLetterPDF(letterData, userInfo, category) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 25;
  const contentWidth = pageWidth - 2 * margin;

  const today = new Date();
  const dateStr = today.toLocaleDateString('en-IN', { day: '2-digit', month: '2-digit', year: 'numeric' });
  const fileNameDate = today.toLocaleDateString('en-IN', { day: '2-digit', month: '2-digit', year: 'numeric' }).replace(/\//g, '');

  // ============ PAGE 1: LETTER ============
  // Dark navy header
  doc.setFillColor(10, 14, 26);
  doc.rect(0, 0, pageWidth, 15, 'F');

  // VaakSakshi title
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('VaakSakshi', margin, 10);

  // AI-Powered subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('AI-Powered Legal Letter', pageWidth - margin - 35, 10);

  // Letter content
  doc.setTextColor(31, 41, 55);
  doc.setFont('times', 'normal');
  doc.setFontSize(11);

  const lineHeight = 7;
  let yPos = 30;

  // Split letter body into lines
  const lines = doc.splitTextToSize(letterData.letter_body, contentWidth);

  for (let i = 0; i < lines.length; i++) {
    if (yPos > pageHeight - 20) {
      // Add page number
      doc.setFontSize(9);
      doc.setTextColor(128, 128, 128);
      doc.text(`Page 1 of ${letterData.letter_body.length > 1500 ? '3' : '2'}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
      doc.text(`Generated by VaakSakshi | ${dateStr}`, margin, pageHeight - 10);

      doc.addPage();
      yPos = 20;
    }
    doc.text(lines[i], margin, yPos);
    yPos += lineHeight;
  }

  // Page 1 footer
  const totalPages = letterData.letter_body.length > 1500 ? 3 : 2;
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text(`Page 1 of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  doc.text(`Generated by VaakSakshi | ${dateStr}`, margin, pageHeight - 10);

  // ============ PAGE 2: FILING INSTRUCTIONS ============
  doc.addPage();

  // Header
  doc.setFillColor(10, 14, 26);
  doc.rect(0, 0, pageWidth, 15, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('How to File This Complaint', margin, 10);

  yPos = 30;
  doc.setTextColor(31, 41, 55);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Where to File:', margin, yPos);
  yPos += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(letterData.filing_instructions.where_to_file, margin, yPos);
  yPos += 10;

  if (letterData.filing_instructions.portal_url) {
    doc.setTextColor(99, 102, 241);
    doc.text(letterData.filing_instructions.portal_url, margin, yPos);
    yPos += 15;
  }

  doc.setTextColor(31, 41, 55);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Steps to File:', margin, yPos);
  yPos += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  letterData.filing_instructions.how_to_file.forEach((step, index) => {
    if (yPos > pageHeight - 25) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(`${index + 1}. ${step}`, margin, yPos);
    yPos += 8;
  });

  yPos += 5;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Documents Needed:', margin, yPos);
  yPos += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  letterData.filing_instructions.documents_needed.forEach((docItem) => {
    if (yPos > pageHeight - 25) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(`☐ ${docItem}`, margin, yPos);
    yPos += 7;
  });

  yPos += 5;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Fee Required:', margin, yPos);
  yPos += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(letterData.filing_instructions.fee_required, margin, yPos);
  yPos += 15;

  // Deadline box
  doc.setDrawColor(239, 68, 68);
  doc.setFillColor(254, 242, 242);
  doc.roundedRect(margin, yPos - 5, contentWidth, 15, 3, 3, 'F');
  doc.setDrawColor(239, 68, 68);
  doc.roundedRect(margin, yPos - 5, contentWidth, 15, 3, 3, 'S');

  doc.setTextColor(220, 38, 38);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(`Deadline: ${letterData.filing_instructions.deadline || letterData.time_limit_to_file}`, margin + 3, yPos + 5);

  // Page 2 footer
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text(`Page 2 of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  doc.text(`Generated by VaakSakshi | ${dateStr}`, margin, pageHeight - 10);

  // ============ PAGE 3: STRENGTH ASSESSMENT ============
  if (totalPages === 3) {
    doc.addPage();

    // Header
    doc.setFillColor(10, 14, 26);
    doc.rect(0, 0, pageWidth, 15, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Legal Assessment', margin, 10);

    yPos = 30;

    // Strength badge
    const strengthColor = letterData.strength_assessment === 'STRONG' ? [34, 197, 94] :
                          letterData.strength_assessment === 'MODERATE' ? [234, 179, 8] : [239, 68, 68];

    doc.setFillColor(...strengthColor);
    doc.roundedRect(margin, yPos - 5, 40, 10, 2, 2, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(letterData.strength_assessment, margin + 5, yPos + 2);

    yPos += 15;
    doc.setTextColor(31, 41, 55);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);

    const strengthLines = doc.splitTextToSize(letterData.strength_reason, contentWidth);
    strengthLines.forEach((line) => {
      doc.text(line, margin, yPos);
      yPos += 7;
    });

    yPos += 10;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Key Laws Cited:', margin, yPos);
    yPos += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    letterData.key_laws_cited.forEach((law) => {
      doc.text(`• ${law}`, margin + 5, yPos);
      yPos += 6;
    });

    yPos += 10;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Expected Outcome:', margin, yPos);
    yPos += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    const outcomeLines = doc.splitTextToSize(letterData.expected_outcome, contentWidth);
    outcomeLines.forEach((line) => {
      doc.text(line, margin, yPos);
      yPos += 7;
    });

    // Disclaimer box
    yPos += 10;
    doc.setDrawColor(75, 85, 99);
    doc.setFillColor(243, 244, 246);
    doc.roundedRect(margin, yPos - 5, contentWidth, 25, 3, 3, 'F');
    doc.setDrawColor(75, 85, 99);
    doc.roundedRect(margin, yPos - 5, contentWidth, 25, 3, 3, 'S');

    doc.setTextColor(107, 114, 128);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    const disclaimerLines = [
      'Disclaimer: This letter is generated by VaakSakshi AI based on the information provided.',
      'Please review all details carefully before submitting. This is not legal advice.',
      'For complex legal matters, please consult a qualified advocate.',
    ];
    disclaimerLines.forEach((line) => {
      doc.text(line, margin + 3, yPos);
      yPos += 6;
    });

    // Page 3 footer
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(`Page 3 of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text(`Generated by VaakSakshi | ${dateStr}`, margin, pageHeight - 10);
  }

  // Generate filename
  const filename = `VaakSakshi-${category}-Complaint-${fileNameDate}.pdf`;

  return { doc, filename };
}
